// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { Subject } from "./Subject";

export type ActivityEntry = { id: string, at: number, subject: Subject, action: Action, 
/**
 * Id of the pen, ink or swatch. It may no longer exist after a deletion.
 */
subject_id: string, 
/**
 * Display name at the time of the event, so entries stay readable after renames or deletions.
 */
label: string, 
/**
 * For ink changes: the ink before and after.
 */
previous_ink_id: string | null, ink_id: string | null, 
/**
 * What changed, in plain words, when the detail level records it.
 */
changes: Array<string>, };
