// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityDetail } from "./ActivityDetail";
import type { Retention } from "./Retention";

export type ActivitySettings = { 
/**
 * Also applies to finished fills: pruning activity prunes ink history with it.
 */
retention: Retention, detail: ActivityDetail, record_pen_changes: boolean, record_ink_changes: boolean, record_swatches: boolean, record_deletions: boolean, };
