// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupFrequency } from "./BackupFrequency";

export type BackupSettings = { frequency: BackupFrequency, 
/**
 * Automatic backups kept before the oldest is deleted.
 */
keep: number, keep_replaced_photos: boolean, validate_on_import: boolean, };
