// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A backup file found in the scheduled-backups folder.
 */
export type BackupFile = { file_name: string, created_at: number, bytes: number, };
