// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One changed field of a pen, ink or swatch. The interface words it.
 */
export type Change = { 
/**
 * The field's name as stored, e.g. `sheen` or `price`.
 */
field: string, 
/**
 * The value before and after, recorded only with detailed activity and
 * never for notes or photos.
 */
values: [JsonValue, JsonValue] | null, };
