// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityEntry } from "./ActivityEntry";
import type { Fill } from "./Fill";
import type { Ink } from "./Ink";
import type { Pen } from "./Pen";
import type { Settings } from "./Settings";
import type { Swatch } from "./Swatch";

export type Collection = { schema_version: number, pens: Array<Pen>, inks: Array<Ink>, swatches: Array<Swatch>, 
/**
 * Every time a pen was inked. An open fill (no `emptied_at`) is a pen's current ink.
 */
fills: Array<Fill>, activity: Array<ActivityEntry>, settings: Settings, };
