// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandError = { "code": "not_found", kind: string, id: string, } | { "code": "already_inked" } | { "code": "not_inked" } | { "code": "ink_in_use" } | { "code": "too_early" } | { "code": "nothing_to_undo" };
