// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ink } from "./Ink";
import type { Pen } from "./Pen";
import type { Settings } from "./Settings";
import type { Swatch } from "./Swatch";

/**
 * One change requested by the interface.
 */
export type Command = { "type": "ink_pen", pen_id: string, ink_id: string, 
/**
 * When it happened; defaults to now. Used to record a past inking.
 */
at: number | null, note: string, } | { "type": "flush_pen", pen_id: string, at: number | null, } | { "type": "undo_ink_change", pen_id: string, at: number, } | { "type": "save_pen", pen: Pen, } | { "type": "delete_pen", id: string, } | { "type": "save_ink", ink: Ink, } | { "type": "delete_ink", id: string, } | { "type": "save_swatch", swatch: Swatch, } | { "type": "delete_swatch", id: string, } | { "type": "update_settings", settings: Settings, };
