// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateFormat } from "./DateFormat";
import type { InkKind } from "./InkKind";

export type Defaults = { 
/**
 * ISO 4217 code, e.g. "USD".
 */
currency: string, date_format: DateFormat, nib_size: string, nib_material: string, ink_kind: InkKind, };
