// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One period of a pen holding one ink.
 */
export type Fill = { id: string, pen_id: string, ink_id: string, inked_at: number, 
/**
 * `None` while the pen still holds this ink.
 */
emptied_at: number | null, note: string, };
