// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A photo attached to a pen, ink or swatch.
 *
 * Cards show the photo cropped to a fixed frame around (`focus_x`, `focus_y`),
 * enlarged by `zoom`. The stored file itself is never altered.
 */
export type Image = { id: string, 
/**
 * Path relative to the images folder, e.g. `pens/pilot-custom-74.webp`.
 */
path: string, primary: boolean, 
/**
 * Clockwise rotation in degrees: 0, 90, 180 or 270.
 */
rotation: number, 
/**
 * Horizontal focus point, 0.0 (left) to 1.0 (right).
 */
focus_x: number, 
/**
 * Vertical focus point, 0.0 (top) to 1.0 (bottom).
 */
focus_y: number, 
/**
 * Crop zoom, 1.0 (no zoom) to [`Image::MAX_ZOOM`].
 */
zoom: number, };
