// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseType } from "./BaseType";
import type { Flow } from "./Flow";
import type { Image } from "./Image";
import type { InkKind } from "./InkKind";
import type { Level } from "./Level";
import type { PaperBehavior } from "./PaperBehavior";
import type { Sheen } from "./Sheen";
import type { Shimmer } from "./Shimmer";
import type { WaterResistance } from "./WaterResistance";

export type Ink = { id: string, brand: string, 
/**
 * Product line, e.g. "Iroshizuku". Empty when the ink has none.
 */
line: string, name: string, kind: InkKind, volume_ml: number | null, 
/**
 * Number of bottles, samples or cartridges owned.
 */
amount: number, price: number | null, 
/**
 * Main color as `#rrggbb`.
 */
base_color: string, 
/**
 * Sheen color as `#rrggbb`, when the ink has a noticeably different one.
 */
sheen_color: string | null, shimmer: Shimmer, sheen: Sheen, shading: Level, water_resistance: WaterResistance, flow: Flow, lubrication: Level, dry_time_seconds: number | null, base_types: Array<BaseType>, paper: Array<PaperBehavior>, notes: string, 
/**
 * Show these notes on the public showcase (also needs `ShowcaseSettings::show_notes`).
 */
notes_public: boolean, images: Array<Image>, created_at: number, updated_at: number, };
