// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Strength scale used for shading and lubrication.
 */
export type Level = "none" | "low" | "medium" | "high";
