// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Manifest = { kind: string, schema_version: number, app_version: string, created_at: number, 
/**
 * Why the backup was made: "manual", "scheduled", "before-restore".
 */
reason: string, pens: number, inks: number, swatches: number, photos: number, };
