// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a command changed besides the collection itself.
 */
export type Outcome = { 
/**
 * Photos no longer referenced by anything; the caller may delete or archive them.
 */
unused_images: Array<string>, };
