// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Image } from "./Image";

export type Pen = { id: string, brand: string, model: string, 
/**
 * The maker's name for the finish, e.g. "Green Stripe".
 */
color_name: string, 
/**
 * Body colors as `#rrggbb`, used to draw the pen when it has no photo.
 */
colors: Array<string>, 
/**
 * Free text, e.g. "F", "1.5 mm", "Stub".
 */
nib_size: string, 
/**
 * Free text, e.g. "Steel", "14k gold".
 */
nib_material: string, body_material: string, 
/**
 * How the pen takes ink; a pen may take several, e.g. "Cartridge" and "Converter".
 */
filling_systems: Array<string>, price: number | null, 
/**
 * `YYYY-MM-DD` or `YYYY-MM`.
 */
purchased_on: string | null, purchased_from: string, notes: string, 
/**
 * Show these notes on the public showcase (also needs `ShowcaseSettings::show_notes`).
 */
notes_public: boolean, images: Array<Image>, created_at: number, updated_at: number, };
