// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateFormat } from "./DateFormat";
import type { Fill } from "./Fill";
import type { Ink } from "./Ink";
import type { InkSort } from "./InkSort";
import type { Pen } from "./Pen";
import type { PenSort } from "./PenSort";
import type { PublicActivity } from "./PublicActivity";
import type { Swatch } from "./Swatch";
import type { SwatchSort } from "./SwatchSort";
import type { Theme } from "./Theme";

export type PublicCollection = { title: string, theme: Theme, date_format: DateFormat, 
/**
 * Only present when prices are shown.
 */
currency: string | null, 
/**
 * Which sections visitors see, so the interface can tell "hidden" from "empty".
 */
show_pens: boolean, show_inks: boolean, show_swatches: boolean, 
/**
 * The full activity list; with only `show_recent_activity`, the latest few entries.
 */
show_activity: boolean, show_recent_activity: boolean, show_stats: boolean, show_charts: boolean, show_activity_filters: boolean, pen_sort: PenSort, ink_sort: InkSort, swatch_sort: SwatchSort, pens: Array<Pen>, inks: Array<Ink>, swatches: Array<Swatch>, fills: Array<Fill>, activity: Array<PublicActivity>, };
