// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { Subject } from "./Subject";

/**
 * An activity entry stripped to what happened, when, and to which visible item.
 */
export type PublicActivity = { at: number, subject: Subject, action: Action, 
/**
 * Empty when the item is not visible (or no longer exists).
 */
subject_id: string, 
/**
 * The ink involved, when inks are visible.
 */
ink_id: string | null, 
/**
 * For re-inks and flushes: the ink that came out, when inks are visible.
 */
previous_ink_id: string | null, };
