// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A published release.
 */
export type Release = { 
/**
 * Such as `3.0.2`, without the tag's `v`.
 */
version: string, 
/**
 * The release page on GitHub.
 */
url: string, };
