// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How long activity and finished fills are kept.
 */
export type Retention = { "keep": "forever" } | { "keep": "days", "days": number };
