// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivitySettings } from "./ActivitySettings";
import type { BackupSettings } from "./BackupSettings";
import type { Defaults } from "./Defaults";
import type { ShowcaseSettings } from "./ShowcaseSettings";
import type { Theme } from "./Theme";

export type Settings = { theme: Theme, open_items_in_edit_mode: boolean, confirm_destructive_actions: boolean, activity: ActivitySettings, defaults: Defaults, backups: BackupSettings, showcase: ShowcaseSettings, };
