// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InkSort } from "./InkSort";
import type { PenSort } from "./PenSort";
import type { SwatchSort } from "./SwatchSort";
import type { Theme } from "./Theme";

export type ShowcaseSettings = { 
/**
 * Whether visitors who are not signed in can see anything at all. Off by
 * default: the collection stays private until the owner opens it.
 */
enabled: boolean, title: string, theme: Theme, show_pens: boolean, show_inks: boolean, show_swatches: boolean, show_prices: boolean, 
/**
 * Master switch for notes: when off, no notes are public, whatever each item says.
 */
show_notes: boolean, show_stats: boolean, show_charts: boolean, show_activity: boolean, show_activity_filters: boolean, show_recent_activity: boolean, pen_sort: PenSort, ink_sort: InkSort, swatch_sort: SwatchSort, };
