// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatsRange } from "./StatsRange";

export type StatsSettings = { 
/**
 * The period Stats opens with, for the owner and for visitors.
 */
default_range: StatsRange, };
