// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Image } from "./Image";

export type Swatch = { id: string, ink_id: string, paper: string, nib: string, 
/**
 * `YYYY-MM-DD`.
 */
sampled_on: string | null, notes: string, 
/**
 * Show these notes on the public showcase (also needs `ShowcaseSettings::show_notes`).
 */
notes_public: boolean, images: Array<Image>, created_at: number, updated_at: number, };
