// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Release } from "./Release";

/**
 * What Settings shows about updates.
 */
export type UpdateStatus = { 
/**
 * The running version.
 */
current: string, 
/**
 * False when checking is turned off in Settings.
 */
checking: boolean, 
/**
 * The latest release, once a check has succeeded.
 */
latest: Release | null, 
/**
 * When the latest release was last checked successfully.
 */
checked_at: number | null, 
/**
 * Whether `latest` is newer than `current`.
 */
available: boolean, };
